# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Tests

on:
  push:
    branches:
      - 'develop'
      - 'trunk'
  pull_request:
    branches:
      - '**'

permissions: {}

jobs:
  build:
    strategy:
      matrix:
        php:
          - '8.4'
          - '8.0'
      fail-fast: false
    name: Tests / PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions: {}
    steps:
    - name: Checkout repository
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        persist-credentials: false

    - name: Install PHP
      uses: shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1 # v2.36.0
      with:
        php-version: ${{ matrix.php }}
        ini-file: development
        coverage: none
        tools: parallel-lint

    - name: Get Composer cache directory
      id: composer-cache
      run: | #shell
        echo dir="$(composer config cache-files-dir)" >> "$GITHUB_OUTPUT"

    - name: Cache PHP Dependencies
      uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ matrix.php }}-${{ hashFiles('composer.json') }}

    - name: Check source code for syntax errors
      run: composer exec --no-interaction -- parallel-lint bin/ src/ tests/

    - name: Install PHP Dependencies
      run: | #shell
        composer install --prefer-dist --no-progress --no-interaction

    - name: Run the tests
      run: | #shell
        composer test
