name: Tests

on:
  push:
    branches:
      - 'develop'
      - 'trunk'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    strategy:
      matrix:
        php: ['7.4', '8.0', '8.1']
      fail-fast: false
    name: PHP Coding Standards
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install PHP
      uses: shivammathur/setup-php@2.16.0
      with:
        php-version: ${{ matrix.php }}
        coverage: none

    - name: Get Composer Cache Directory
      id: composer-cache-dir
      run: |
        echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Cache PHP Dependencies
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.composer-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ matrix.php }}-${{ hashFiles('composer.json') }}

    - name: Install PHP Dependencies
      run: |
        composer update --prefer-dist --no-progress --no-interaction

    - name: Run the tests
      run: |
        composer test

    - name: Test exported files
      run: |
        mkdir -p tests/cache/ourselves
        echo '{"repositories":[{"type":"path","url":"../../../","options":{"symlink":false}}],"minimum-stability":"dev"}' >tests/cache/ourselves/composer.json
        composer require --working-dir=tests/cache/ourselves 'johnbillion/args:*'
        EXPECTED_FILES="composer.json,CONTRIBUTING.md,FUNDING.yml,generate.php,LICENSE,phpcs.xml.dist,phpstan.neon.dist,phpunit.xml.dist,README.md,shape.php,shapes.php,tests.yml"
        CURRENT_FILES="$(find tests/cache/ourselves/vendor/johnbillion/args/ -type f -not -path 'tests/cache/ourselves/vendor/johnbillion/args/src/*' -printf '%f\0'|sort -z|paste -s -z -d ",")"
        test "$EXPECTED_FILES" == "$CURRENT_FILES"
