# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Tests

on:
  push:
    branches:
      - 'develop'
      - 'trunk'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    strategy:
      matrix:
        php: ['7.4', '8.0', '8.1']
      fail-fast: false
    name: PHP Coding Standards
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install PHP
      uses: shivammathur/setup-php@2.19.1
      with:
        php-version: ${{ matrix.php }}
        ini-file: development
        coverage: none

    - name: Debugging
      run: |
        php --version
        php -m

    - name: Get Composer Cache Directory
      id: composer-cache-dir
      run: |
        echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Cache PHP Dependencies
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ matrix.php }}-${{ hashFiles('composer.json') }}

    - name: Install PHP Dependencies
      run: |
        composer update --prefer-dist --no-progress --no-interaction

    - name: Run the tests
      run: |
        composer test
